version: '3.8'
services:
  unleash:
    image: unleashorg/unleash-server:latest
    pull_policy: always
    ports:
      - '4242:4242'
    environment:
      DATABASE_URL: 'postgres://postgres:unleash@db/db'
      DATABASE_SSL: 'false'
      INIT_ADMIN_API_TOKENS: '*:*.super-secret-admin-token'
      INIT_CLIENT_API_TOKENS: 'default:development.unleash-insecure-api-token'
      LOG_LEVEL: debug
    depends_on:
      - db
    command: ['node', 'index.js']
  db:
    expose:
      - '5432'
    image: postgres:15
    environment:
      POSTGRES_DB: 'db'
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    healthcheck:
      test:
        [
          'CMD',
          'pg_isready',
          '--username=postgres',
          '--host=127.0.0.1',
          '--port=5432',
        ]
      interval: 2s
      timeout: 1m
      retries: 5
      start_period: 10s
  proxy:
    image: unleashorg/unleash-proxy:latest
    pull_policy: always
    ports:
      - '3000:3000'
    environment:
      UNLEASH_URL: 'http://unleash:4242/api'
      UNLEASH_API_TOKEN: 'default:development.unleash-insecure-api-token'
      UNLEASH_PROXY_CLIENT_KEYS: 'insecure-client-key'
      EXP_SERVER_SIDE_SDK_CONFIG_TOKENS: 'server-side-sdk-token'
    depends_on:
      - unleash
